{% set name = "PyJWT" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57e28d156e3d5c10088e0c68abb90bfac3df82b40a71bd0daa20c65ccd5c23de

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing_extensions # [py<=37]
  run_constrained:
    - cryptography >=3.4.0

test:
  source_files:
    - tests
  imports:
    - jwt
  requires:
    - pip
    - pytest >=6.0.0,<7.0.0
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/jpadilla/pyjwt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JSON Web Token implementation in Python
  description: |
    PyJWT is a Python library which allows you to encode and decode JSON Web Tokens (JWT). 
    JWT is an open, industry-standard (RFC 7519) for representing claims securely between two parties.
  dev_url: https://github.com/jpadilla/pyjwt
  doc_url: https://pyjwt.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
