travis:
  secure:
    BINSTAR_TOKEN: XBJPAaeQtj+7q1r2MtVErmxJ9vs/EY2crgyT0oMFjYx+VE+Gf2M59LeVlKDOoP33z2ncdt3nidAvSPkA2tWPMxBbBRCKtS1CZIqbBzkeA9Q+Km+sLpLdvXWwlRAlRjxJ9GDkXL7ilhlFPbhSLIfBA/Pi+dkv88dQZeNLahe9g+QYKxaaHw7VDGGjzWBdIIDkI5poeb2+0eQ1DXRLgrqRXVaiVhd9acnoSOTMtPVyLJaL57aHg+XcE9Ht8M+lbEQfs2a2GXQB5OryhomJe0V7TRMU9x5gM4+inI9FlxQ/QKKcoIQ0IYwJ+2ATB4beuTiPlwt1RZlkwRfzuo8l8PPerZ0MUVtnQWftPLqKzxa5YJtWFq8spxfzpfi644r6xULb5wvyOB2bz+KrnZIDjznEU5WPjaphUF7v+17Jpxw3YoAtZfyLclc8lmVn15GqKsBtGWbt7cGFbl7iVeWacVC5Fw+QeEECwx333RfNntXa108mGtnbMwbNTabMmTi1JLmiZaDRHDbR6HGKRH82AjFMyEylmpIoMQOlkrqXw67STuCs1rtZ9mXsUfSt3dWd5qpXx79nxKYHS17pP7PhYEYbN2qxWx7Da9qy2X+BbiqT56BhN20uERZLqLbcClfP/yOCDnYKWHLD25Vcy/o9MrnBbo09mpBGeZuFmvksnCJJTB0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
