travis:
  secure:
    BINSTAR_TOKEN: h8h+GVDSUF2WYl/w6nuan7kuhXo7h1NF04D9AgTMu4bFI5zMTqmoJQyFhIawksFRly8ZzKT4nRNNJp+Hgjr1EBKsmO47KHWAhEwE2MpOvVl2PMBnZXu5hO7oRbmF4ArO5Lam86tCmAoSBSXNSD2k320Oj+dNi6Wp0Gq7ki3buLjirsvHmnrksxx5guCutLxnv16Y6lnE+zKjmR0j6REglqINCdINuYLwsZyDkhbHsvvjft7/XAPLp7Ck07h7uotG8foB4w2xV7htwnhaf9kIz5wHAK8gMDCvQH39dJ8NbF0uLWf0CMekiuF0FNrQeHnAA9mb3aL0Nk4ik38x+5yraMSM3dVzRzvUqr5Ydl3ZmhNNwB09Uy2HBbTppr5Pui4pDK6i7vwyhFo6B/fCOW9ff0aFKZvz9xcI9fBL9UnLkbNniK/K6ReVSbd96Ffo+bx34SYEhtRZ/+hkmwa3tYf+dGDrAXrOAkS29Gh86Bm9WsDwNxhA9ZfYucrI4+ySk9+T+WzmzYrp3mDV6LzqE9/zILTeCq8T1RrNGqdxvEoE8WaF4oxLDspRyGaRLEXl7F6Ee66lsMongtSyfCxp/jjdqVjWCvt4Fsny1bSGkMCpxoo7FEc5SgKtdv9HjvSw3RK7UlDL0VdVWDUn3KO7RsNtmALdk/lW+pyu8kiVd8o+Ja4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
